//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBrowser.SettingsFiles {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Favourites : global::System.Configuration.ApplicationSettingsBase {
        
        private static Favourites defaultInstance = ((Favourites)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Favourites())));
        
        public static Favourites Default {
            get {
                return defaultInstance;
            }
        }
    }
}
